backend:
  name: git-gateway
  branch: main

media_folder: "_site/assets/images"
public_folder: "/assets/images"

collections:
  - name: "services"
    label: "Homepage Services"
    folder: "src/services"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: description, label: Description, widget: text }
      - { name: img, label: Image, widget: image }

  - name: "pages"
    label: "Pages"
    files:
      - label: "HomePage"
        name: "home"
        file: "src/index.md"
        fields:
          - {
              name: "layout",
              label: "Layout",
              widget: "hidden",
              default: "homepage.njk",
            }
          - { label: "Meta Title", name: "title", widget: "string" }
          - {
              name: "hero",
              label: "Hero",
              widget: "object",
              fields:
                [
                  { label: "Background Image", name: "bg", widget: "image" },
                  {
                    label: "First Title Paragraph",
                    name: "firstTitlepara",
                    widget: "string",
                  },
                  {
                    label: "Second Title Paragraph",
                    name: "secondTitlepara",
                    widget: "string",
                  },
                  { label: "Paragraph", name: "Para", widget: "string" },
                ],
            }
          - {
              name: "OurMission",
              label: "Our Mission",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string" },
                  { label: "Paragraph", name: "paragraph", widget: "markdown" },
                  {
                    label: "Mission Image",
                    name: "missionimage",
                    widget: "image",
                  },
                ],
            }

      - label: "About Page"
        name: "about"
        file: "src/about-94-ft-player-deployment.md"

        fields:
          - { label: "Meta Title", name: "title", widget: "string" }
          - { label: "Heading", name: "heading", widget: "string" }
          - {
              label: "Background Image",
              name: "backgroundImage",
              widget: "image",
            }
          - {
              label: "History Heading",
              name: "HistoryHeading",
              widget: "string",
            }
          - { label: "Span Text", name: "SpanText", widget: "string" }
          - { label: "History", name: "history", widget: "markdown" }
          - { label: "Owner Image", name: "OwnerImage", widget: "image" }
          - {
              label: "Owner Bio 1",
              name: "OwnerBioparagraphOne",
              widget: "markdown",
            }
          - {
              label: "Owner Bio 2",
              name: "OwnerBioparagraphTwo",
              widget: "markdown",
            }
          - {
              name: "layout",
              label: "Layout",
              widget: "hidden",
              default: "about.njk",
            }
